# Generated by Django 6.0.6 on 2026-06-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
